### ISSUE TITLE
Exception thrown when going to calm a pawn that stops being mad

### ISSUE THREAD

**Issue by ErnestUTN** [Weilbyte/SnapOut#10]
When a fight broke up between two pawns, I sent one of my guys to try to calm one of them down, but before he reached the target guy, this one stopped being mad and an exception was thrown, namely this:

```
Exception in SetupToils for pawn Builder driver=JobDriver_GoToSafety (toilIndex=1) driver.job=(SnapOut_GoToSafetyJob (Job_3469289) B=Thing_Human983) lastJobGiver=null
System.NullReferenceException: Object reference not set to an instance of an object
  at SnapOut.JobDriver_GoToSafety+<MakeNewToils>d__1.MoveNext () [0x00000] in <filename unknown>:0 
  at Verse.AI.JobDriver.SetupToils () [0x00000] in <filename unknown>:0 
```

I think there's a missing null check conditional in your code?

Regards

**Comment by Weilbyte** [comment]
Thanks! I'll look into it.
Does the pawn in question have a bedroom?

**Comment by Weilbyte** [comment]
I was able to reproduce the issue and am currently working on a fix.
Thanks!

**Comment by Weilbyte** [comment]
Fix included in new release.

**Comment by ErnestUTN** [comment]
Thanks Weil!. Sry I wasn't here to answer the bedroom question, but it would have been yes!.
Neat!, glad you could fix it :D
