### ISSUE TITLE
Got error when trying to calm down a sleeping pawn.

### ISSUE THREAD

**Issue by Leslov** [Weilbyte/SnapOut#13]
One of pawn got "Apathy". In this mental state she did regular daily work (building, eating, sleeping). When she was sleeping other pawn trying to calm down her but got multiple exact errors "started 10 jobs in one tick". Job name is CalmDownJob (1057812)
![image](https://user-images.githubusercontent.com/15822720/76946666-32ca1680-6926-11ea-8bb3-c0bd058caaf6.png)

**Comment by Weilbyte** [comment]
Which version of the game are you running and which release do you use (Steam or non-steam)?

**Comment by Leslov** [comment]
Steam 1.0

**Comment by Weilbyte** [comment]
How often does the error happen? They shouldn't be able to calm down sleeping pawns.

**Comment by Leslov** [comment]
Very rare. Yes, they can't calm down sleeping pawns but they trying to do so. Maybe SnapOut conflict with other mods. I'm currently playing with collection of mods including Psychology

**Comment by Weilbyte** [comment]
Probably a conflict, as it happens rarely I dont think theres much I can do. Do you happen to run any other mods that affect moods and breakdowns? (Apart from Psychology)
