### ISSUE TITLE
error on launching

### ISSUE THREAD

**Issue by Yaksinikos** [Weilbyte/SnapOut#14]
error on launching;
[Gist](https://gist.github.com/Translator5/bdc0db65186bc6af9b3d4a3db9ecc2fd)

**Comment by Weilbyte** [comment]
Hello!
Please provide source (Steam/GitHub) and game version.

**Comment by Yaksinikos** [comment]
1.1.2571 (64-bit)
Manjaro Linux
May mod conflict with WorkTab, Hospitality etc.?

**Comment by Weilbyte** [comment]
Should work fine on Linux. Unsure whether it conflicts with WorkTab, and compatible with Hospitality. I'll do some code refactoring soon and will include some stuff that might fix this issue.

**Comment by Weilbyte** [comment]
Sorry for late response. Could not replicate.  
Try the latest update and re-open if issue still present with it. 

Build on Linux so you should not have issues because of that.
