### ISSUE TITLE
Error:  ... tried to do interaction ... only x ticks since last interaction 

### ISSUE THREAD

**Issue by ghost** [Weilbyte/SnapOut#21]
Gecko tried to do interaction SnapOut_CalmDownInteraction to Tachikoma only 118 ticks since last interaction (min is 120).
Verse.Log:Error(String, Boolean)
RimWorld.Pawn_InteractionsTracker:TryInteractWith(Pawn, InteractionDef)
SnapOut.<>c__DisplayClass2_0:<AttemptCalm>b__0()
Verse.AI.JobDriver:TryActuallyStartNextToil()
Verse.AI.JobDriver:ReadyForNextToil()
Verse.AI.JobDriver:Verse.AI.JobDriver.DriverTick_Patch1(JobDriver)
Verse.AI.Pawn_JobTracker:JobTrackerTick()
Verse.Pawn:Verse.Pawn.Tick_Patch2(Pawn)
Verse.TickList:Tick()
Verse.TickManager:Verse.TickManager.DoSingleTick_Patch1(TickManager)
Verse.TickManager:Verse.TickManager.TickManagerUpdate_Patch2(TickManager)
Verse.Game:UpdatePlay()
Verse.Root_Play:Update()

**Comment by Weilbyte** [comment]
Known bug that rarely happens, safe to ignore. 
Just curious, is the pawn a prisoner that has recently been interacted with?

**Comment by ghost** [comment]
I don't think so, just my colonist, can it be fixed?

**Comment by Weilbyte** [comment]
Can be tricky. How often does this happen?

**Comment by ghost** [comment]
First time, i'm used calm pawn after it already did someone, something like that

**Comment by Weilbyte** [comment]
Oh, safe to ignore. The issue is that for the calm-down cool down my mod piggybacks off of the prisoner/pawn interaction timer, and rarely the timing is just right that that error comes up.

**Comment by ghost** [comment]
Finally fixed?
