### ISSUE TITLE
Replace UnityEngine.Random with Verse.Rand inside of JobDriver_GoToSafety for Multiplayer compaatibility

### ISSUE THREAD

**Issue by SokyranTheDragon** [Weilbyte/SnapOut#36]
In general, Multiplayer doesn't like System/Unity RNG. There are some exceptions, but in general it's safer to use it anyway. So unless this method has been tested in Multiplayer and wasn't causing issues, I'd replace the RNG.

So, tl;dr replace
`int wticks = UnityEngine.Random.Range(1750, 3500);`
with
`int wticks = Rand.Range(1750, 3500);`

**Comment by Weilbyte** [comment]
Oh I must've missed that. But wouldn't `Rand.RangeSeeded` be better for this?

**Comment by SokyranTheDragon** [comment]
Speaking as someone who works a lot with MP and on patching mods for MP: seeded is the safest for MP, but (in most cases) even unseeded could work (since it's deterministic and all) - as long as the method is called at the same time for all players, the internal RNG will be the same for all.

Now, if there's something that messes with the RNG state, then seeded will save you there. But it'll pop up somewhere else most likely.

Well, I like to overexplain... Tl;dr - in most cases, it's fine if unseeded. But not always. For example, I noticed when creating motes it's causing issues.


As a side note: if you surround your RNG calls with `Rand.PushState(int seed)` and `Rand.PopState()`, it'll make all of the methods between those 2 calls seeded.

**Comment by Weilbyte** [comment]
Will hopefully get to this next week when I have time. Thanks for pointing it out.

**Comment by Weilbyte** [comment]
Wasn't exactly "next week" 👀
